"""Observability stack for IATB - Logging, Tracing, Metrics, and Alerting."""

from iatb.core.observability.alerting import (
    TelegramAlerter,
    TelegramAlertLevel,
    get_alerter,
)
from iatb.core.observability.logging_config import (
    LogContext,
    get_logger,
    setup_structured_logging,
)
from iatb.core.observability.metrics import (
    api_request_counter,
    api_request_duration,
    daily_pnl,
    data_source_latency,
    data_source_switches,
    error_counter,
    initialize_metrics,
    instrument_fastapi_app,
    ml_model_status,
    model_inference_duration,
    open_positions,
    portfolio_value,
    record_data_source_latency,
    record_data_source_switch,
    record_error,
    record_model_inference,
    record_scan_cycle,
    record_trade,
    scan_cycle_duration,
    start_metrics_server,
    trade_counter,
    trade_pnl,
    update_broker_connection_status,
    update_daily_pnl,
    update_database_connection_status,
    update_ml_model_status,
    update_open_positions,
    update_portfolio_value,
)
from iatb.core.observability.tracing import (
    SpanContext,
    add_span_attributes,
    get_tracer,
    record_exception,
    setup_tracing,
)

__all__ = [
    # Logging
    "setup_structured_logging",
    "get_logger",
    "LogContext",
    # Tracing
    "setup_tracing",
    "get_tracer",
    "SpanContext",
    "add_span_attributes",
    "record_exception",
    # Metrics
    "initialize_metrics",
    "instrument_fastapi_app",
    "start_metrics_server",
    "record_trade",
    "update_open_positions",
    "update_portfolio_value",
    "update_daily_pnl",
    "record_scan_cycle",
    "record_model_inference",
    "record_data_source_switch",
    "record_data_source_latency",
    "record_error",
    "update_broker_connection_status",
    "update_database_connection_status",
    "update_ml_model_status",
    "trade_counter",
    "trade_pnl",
    "open_positions",
    "portfolio_value",
    "daily_pnl",
    "api_request_duration",
    "api_request_counter",
    "scan_cycle_duration",
    "model_inference_duration",
    "data_source_switches",
    "data_source_latency",
    "error_counter",
    "broker_connection_status",
    "database_connection_status",
    "ml_model_status",
    # Alerting
    "TelegramAlertLevel",
    "TelegramAlerter",
    "get_alerter",
]
