[nse]
symbols = [
    "TEST1",
]

[bse]
symbols = [
    "500325",
    "532540",
    "500209",
    "500180",
    "532174",
    "500112",
    "500124",
    "500770",
    "500820",
    "532500",
]

[mcx]
symbols = [
    "CRUDEOIL",
    "GOLD",
    "SILVER",
    "NATURALGAS",
    "COPPER",
]

[cds]
symbols = [
    "USDINR",
    "EURINR",
    "GBPINR",
    "JPYINR",
]
