[weights.BULL]
sentiment = "0.25"
strength = "0.25"
volume_profile = "0.25"
drl = "0.25"

[weights.BEAR]
sentiment = "0.25"
strength = "0.25"
volume_profile = "0.25"
drl = "0.25"

[weights.SIDEWAYS]
sentiment = "0.25"
strength = "0.25"
volume_profile = "0.25"
drl = "0.25"
