"""
Event definitions for IATB.

Provides immutable dataclass events for the event-driven architecture.
All events include a UUID and strict UTC timestamp for traceability.
"""

from dataclasses import dataclass, field
from datetime import UTC, datetime
from decimal import Decimal
from uuid import UUID, uuid4

from iatb.core.enums import Exchange, OrderSide, OrderStatus, OrderType
from iatb.core.event_validation import validate_event
from iatb.core.exceptions import ValidationError
from iatb.core.types import (
    Price,
    Quantity,
    Timestamp,
    create_price,
    create_quantity,
    create_timestamp,
)


def _utc_now_timestamp() -> Timestamp:
    """Create a strict UTC timestamp for event defaults."""
    return create_timestamp(datetime.now(UTC))


def _enforce_utc_timestamp(timestamp: Timestamp) -> Timestamp:
    """Fail-closed enforcement of strict UTC timestamps at event creation."""
    try:
        return create_timestamp(timestamp)
    except ValueError as exc:
        msg = f"Invalid event timestamp: {exc}"
        raise ValidationError(msg) from exc


@dataclass(frozen=True)
class MarketTickEvent:
    """Event representing a market data tick."""

    event_id: UUID = field(default_factory=uuid4)
    timestamp: Timestamp = field(default_factory=_utc_now_timestamp)
    exchange: Exchange = Exchange.NSE
    symbol: str = "UNKNOWN"
    price: Price = field(default_factory=lambda: create_price("0.0"))
    quantity: Quantity = field(default_factory=lambda: create_quantity("0.0"))
    volume: Quantity = field(default_factory=lambda: create_quantity("0.0"))
    bid_price: Price | None = None
    ask_price: Price | None = None

    def __post_init__(self) -> None:
        """Validate event at creation-time (fail-closed)."""
        object.__setattr__(self, "timestamp", _enforce_utc_timestamp(self.timestamp))
        validate_event(self)


@dataclass(frozen=True)
class OrderUpdateEvent:
    """Event representing an order status update."""

    event_id: UUID = field(default_factory=uuid4)
    timestamp: Timestamp = field(default_factory=_utc_now_timestamp)
    order_id: str = "UNKNOWN_ORDER"
    exchange: Exchange = Exchange.NSE
    symbol: str = "UNKNOWN"
    side: OrderSide = OrderSide.BUY
    order_type: OrderType = OrderType.MARKET
    quantity: Quantity = field(default_factory=lambda: create_quantity("0.0"))
    price: Price | None = None
    filled_quantity: Quantity = field(default_factory=lambda: create_quantity("0.0"))
    avg_price: Price | None = None
    status: OrderStatus = OrderStatus.PENDING

    def __post_init__(self) -> None:
        """Validate event at creation-time (fail-closed)."""
        object.__setattr__(self, "timestamp", _enforce_utc_timestamp(self.timestamp))
        validate_event(self)


@dataclass(frozen=True)
class SignalEvent:
    """Event representing a trading signal generated by strategy."""

    event_id: UUID = field(default_factory=uuid4)
    timestamp: Timestamp = field(default_factory=_utc_now_timestamp)
    strategy_id: str = "UNKNOWN_STRATEGY"
    exchange: Exchange = Exchange.NSE
    symbol: str = "UNKNOWN"
    side: OrderSide = OrderSide.BUY
    quantity: Quantity = field(default_factory=lambda: create_quantity("0.0"))
    price: Price | None = None
    confidence: Decimal = Decimal("0.0")

    def __post_init__(self) -> None:
        """Validate event at creation-time (fail-closed)."""
        object.__setattr__(self, "timestamp", _enforce_utc_timestamp(self.timestamp))
        validate_event(self)


@dataclass(frozen=True)
class RegimeChangeEvent:
    """Event representing a change in market regime."""

    event_id: UUID = field(default_factory=uuid4)
    timestamp: Timestamp = field(default_factory=_utc_now_timestamp)
    regime_type: str = "UNSPECIFIED"
    description: str = "UNSPECIFIED"
    confidence: Decimal = Decimal("0.0")
    metadata: dict[str, str] = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Validate event at creation-time (fail-closed)."""
        object.__setattr__(self, "timestamp", _enforce_utc_timestamp(self.timestamp))
        validate_event(self)


@dataclass(frozen=True)
class ScanUpdateEvent:
    """Event representing a scanner cycle completion with results."""

    event_id: UUID = field(default_factory=uuid4)
    timestamp: Timestamp = field(default_factory=_utc_now_timestamp)
    total_candidates: int = 0
    approved_candidates: int = 0
    trades_executed: int = 0
    duration_ms: int = 0
    errors: list[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        """Validate event at creation-time (fail-closed)."""
        object.__setattr__(self, "timestamp", _enforce_utc_timestamp(self.timestamp))
        validate_event(self)


@dataclass(frozen=True)
class PnLUpdateEvent:
    """Event representing a PnL update after a trade."""

    event_id: UUID = field(default_factory=uuid4)
    timestamp: Timestamp = field(default_factory=_utc_now_timestamp)
    order_id: str = "UNKNOWN"
    symbol: str = "UNKNOWN"
    side: str = "UNKNOWN"
    quantity: Quantity = field(default_factory=lambda: create_quantity("0.0"))
    price: Price = field(default_factory=lambda: create_price("0.0"))
    trade_pnl: Decimal = Decimal("0.0")
    cumulative_pnl: Decimal = Decimal("0.0")

    def __post_init__(self) -> None:
        """Validate event at creation-time (fail-closed)."""
        object.__setattr__(self, "timestamp", _enforce_utc_timestamp(self.timestamp))
        validate_event(self)
