"""Generate the Decimal metrics test file."""
L = [
    "# Tests for Decimal API boundary handling in observability metrics.",
    "from __future__ import annotations",
    "",
    "from decimal import Decimal",
    "",
    "import pytest",
    "",
    "from iatb.core.observability.metrics import (",
    "    _decimal_to_prometheus_gauge_value,",
    "    record_trade,",
    "    update_daily_pnl,",
    "    update_portfolio_value,",
    ")",
    "",
    "",
    "class TestDecimalToPrometheusGaugeValue:",
    "    # Tests for API boundary helper.",
    "    def test_positive_decimal_conversion(self) -> None:",
    '        result = _decimal_to_prometheus_gauge_value(Decimal("100.50"))',
    "        assert result == 100.50",
    "        assert isinstance(result, float)",
    "",
    "    def test_negative_decimal_conversion(self) -> None:",
    '        result = _decimal_to_prometheus_gauge_value(Decimal("-50.25"))',
    "        assert result == -50.25",
    "        assert isinstance(result, float)",
    "",
    "    def test_zero_decimal_conversion(self) -> None:",
    '        result = _decimal_to_prometheus_gauge_value(Decimal("0"))',
    "        assert result == 0.0",
    "        assert isinstance(result, float)",
    "",
    "    def test_large_precision_decimal(self) -> None:",
    '        result = _decimal_to_prometheus_gauge_value(Decimal("999999.9999"))',
    "        assert isinstance(result, float)",
    "        assert result > 0",
    "",
    "    def test_tiny_fractional_decimal(self) -> None:",
    '        result = _decimal_to_prometheus_gauge_value(Decimal("0.0001"))',
    "        assert isinstance(result, float)",
    "        assert result > 0",
    "",
    "    def test_integer_decimal(self) -> None:",
    '        result = _decimal_to_prometheus_gauge_value(Decimal("42"))',
    "        assert result == 42.0",
    "        assert isinstance(result, float)",
    "",
    "",
    "class TestRecordTradeDecimal:",
    "    # Tests for record_trade with Decimal PnL values.",
    "    def test_record_trade_with_decimal_pnl(self) -> None:",
    '        record_trade(exchange="NSE", side="BUY", status="SUCCESS", pnl=Decimal("100.50"), ticker="RELIANCE")',
    "        assert True",
    "",
    "    def test_record_trade_with_none_pnl(self) -> None:",
    '        record_trade(exchange="NSE", side="BUY", status="SUCCESS", pnl=None, ticker="RELIANCE")',
    "        assert True",
    "",
    "    def test_record_trade_with_pnl_no_ticker(self) -> None:",
    '        record_trade(exchange="NSE", side="BUY", status="SUCCESS", pnl=Decimal("100.50"), ticker=None)',
    "        assert True",
    "",
    "    def test_record_trade_with_negative_decimal_pnl(self) -> None:",
    '        record_trade(exchange="NSE", side="SELL", status="SUCCESS", pnl=Decimal("-250.75"), ticker="TCS")',
    "        assert True",
    "",
    "    def test_record_trade_with_zero_decimal_pnl(self) -> None:",
    '        record_trade(exchange="NSE", side="BUY", status="SUCCESS", pnl=Decimal("0"), ticker="INFY")',
    "        assert True",
    "",
    "",
    "class TestUpdatePortfolioValueDecimal:",
    "    # Tests for update_portfolio_value with Decimal values.",
    "    def test_update_portfolio_value_decimal(self) -> None:",
    '        update_portfolio_value(value=Decimal("100000.50"))',
    "        assert True",
    "",
    "    def test_update_portfolio_value_decimal_negative(self) -> None:",
    '        update_portfolio_value(value=Decimal("-5000.00"))',
    "        assert True",
    "",
    "    def test_update_portfolio_value_decimal_zero(self) -> None:",
    '        update_portfolio_value(value=Decimal("0"))',
    "        assert True",
    "",
    "",
    "class TestUpdateDailyPnLDecimal:",
    "    # Tests for update_daily_pnl with Decimal values.",
    "    def test_update_daily_pnl_decimal(self) -> None:",
    '        update_daily_pnl(pnl=Decimal("5000.75"))',
    "        assert True",
    "",
    "    def test_update_daily_pnl_decimal_loss(self) -> None:",
    '        update_daily_pnl(pnl=Decimal("-2000.50"))',
    "        assert True",
    "",
    "    def test_update_daily_pnl_decimal_zero(self) -> None:",
    '        update_daily_pnl(pnl=Decimal("0"))',
    "        assert True",
    "",
]

with open("tests/core/test_observability_metrics_decimal.py", "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(L))
print("OK")