"""
Automated Risk Disclosure Document Generator.

Generates SEBI-compliant risk disclosure documents in HTML and text formats
for algorithmic trading systems, as required for live and enterprise deployment.
"""

import logging
from dataclasses import dataclass
from datetime import UTC, datetime
from decimal import Decimal
from pathlib import Path

from iatb.core.exceptions import ConfigError

_LOGGER = logging.getLogger(__name__)

_DISCLAIMER_TEMPLATE = (
    "ALGORITHMIC TRADING RISK DISCLOSURE\n"
    "=====================================\n\n"
    "This document is generated in compliance with SEBI guidelines for\n"
    "algorithmic trading systems. It discloses the risks associated with\n"
    "automated order execution and risk management controls.\n\n"
    "Generated: {timestamp}\n"
    "System: {system_name}\n"
    "Version: {system_version}\n"
    "Algo ID: {algo_id}\n\n"
    "1. GENERAL RISK WARNING\n"
    "-----------------------\n"
    "Algorithmic trading involves substantial risk of loss and is not\n"
    "suitable for all investors. Past performance is not indicative of\n"
    "future results. The value of investments and the income derived may\n"
    "go down as well as up and investors may not get back the amount\n"
    "originally invested.\n\n"
    "2. TECHNOLOGY RISKS\n"
    "-------------------\n"
    "- System failures, network disruptions, and latency issues may\n"
    "  result in delayed or failed order execution.\n"
    "- Software bugs or configuration errors may cause unintended\n"
    "  trading behavior.\n"
    "- Third-party API dependencies (broker, data provider) may\n"
    "  experience outages affecting trade execution.\n\n"
    "3. MARKET RISKS\n"
    "--------------\n"
    "- Market volatility may result in significant slippage between\n"
    "  expected and actual execution prices.\n"
    "- Gap risk: Prices may gap significantly between trading sessions.\n"
    "- Liquidity risk: Sufficient market depth may not be available\n"
    "  for order fills at desired prices.\n\n"
    "4. RISK CONTROLS IMPLEMENTED\n"
    "----------------------------\n"
    "This system implements the following risk management controls:\n"
    "{risk_controls}\n\n"
    "5. POSITION LIMITS\n"
    "-----------------\n"
    "{position_limits}\n\n"
    "6. CIRCUIT BREAKER AND KILL SWITCH\n"
    "----------------------------------\n"
    "The system includes an automated circuit breaker that halts trading\n"
    "when predefined loss thresholds are exceeded. A manual kill switch\n"
    "is available for immediate trading cessation.\n\n"
    "7. AUDIT TRAIL\n"
    "-------------\n"
    "All orders are logged with cryptographic HMAC-SHA256 hash chain\n"
    "integrity verification for regulatory audit compliance.\n"
    "Audit retention period: {retention_years} years.\n\n"
    "8. COMPLIANCE STATEMENT\n"
    "----------------------\n"
    "This algorithmic trading system operates under SEBI guidelines for\n"
    "automated trading with the following compliance measures:\n"
    "- Static IP registration with broker\n"
    "- OAuth 2FA authentication\n"
    "- Auto-logout at IST cutoff\n"
    "- Algo ID registration\n"
    "- Order rate throttling\n\n"
    "9. ACKNOWLEDGMENT\n"
    "----------------\n"
    "By using this system, the user acknowledges the risks described\n"
    "above and confirms understanding of the risk management controls\n"
    "implemented.\n\n"
    "---\n"
    "This document was auto-generated by IATB Risk Disclosure Generator.\n"
    "Document ID: {doc_id}\n"
    "Generation Timestamp (UTC): {timestamp}\n"
)

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Risk Disclosure - {system_name}</title>
<style>
body {{ font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; }}
h1 {{ color: #333; border-bottom: 2px solid #ccc; padding-bottom: 10px; }}
h2 {{ color: #555; margin-top: 30px; }}
.warning {{ background: #fff3cd; border-left: 4px solid #ffc107; padding: 15px; margin: 20px 0; }}
.controls {{ background: #d4edda; border-left: 4px solid #28a745; padding: 15px; margin: 20px 0; }}
footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #ccc;
color: #666; font-size: 0.9em; }}
</style>
</head>
<body>
<h1>Algorithmic Trading Risk Disclosure</h1>
<p><strong>System:</strong> {system_name} v{system_version}</p>
<p><strong>Algo ID:</strong> {algo_id}</p>
<p><strong>Generated:</strong> {timestamp}</p>
<p><strong>Document ID:</strong> {doc_id}</p>

<div class="warning">
<h2>General Risk Warning</h2>
<p>Algorithmic trading involves substantial risk of loss and is not suitable
for all investors. Past performance is not indicative of future results.</p>
</div>

<h2>Technology Risks</h2>
<ul>
<li>System failures, network disruptions, and latency issues</li>
<li>Software bugs or configuration errors</li>
<li>Third-party API dependency outages</li>
</ul>

<h2>Market Risks</h2>
<ul>
<li>Significant slippage between expected and actual execution prices</li>
<li>Gap risk between trading sessions</li>
<li>Liquidity risk for order fills</li>
</ul>

<div class="controls">
<h2>Risk Controls Implemented</h2>
{risk_controls_html}
</div>

<h2>Position Limits</h2>
{position_limits_html}

<h2>Compliance Statement</h2>
<p>This system operates under SEBI guidelines with: Static IP registration,
OAuth 2FA, Auto-logout at IST cutoff, Algo ID registration, Order throttling.</p>

<footer>
<p>Auto-generated by IATB Risk Disclosure Generator</p>
<p>Document ID: {doc_id} | Timestamp (UTC): {timestamp}</p>
</footer>
</body>
</html>"""


@dataclass(frozen=True)
class RiskDisclosureConfig:
    """Configuration for risk disclosure document generation."""

    system_name: str = "IATB"
    system_version: str = "0.1.0"
    algo_id: str = ""
    retention_years: int = 7
    output_dir: Path = Path("docs/disclosures")

    def __post_init__(self) -> None:
        if not self.system_name.strip():
            msg = "system_name cannot be empty"
            raise ConfigError(msg)
        if self.retention_years <= 0:
            msg = "retention_years must be positive"
            raise ConfigError(msg)


@dataclass(frozen=True)
class PositionLimitDisclosure:
    """Position limit information for disclosure."""

    exchange: str
    max_quantity: Decimal
    max_notional: Decimal


class RiskDisclosureGenerator:
    """Generates SEBI-compliant risk disclosure documents."""

    def __init__(self, config: RiskDisclosureConfig) -> None:
        if not config.algo_id.strip():
            msg = "algo_id is required for risk disclosure"
            raise ConfigError(msg)
        self._config = config
        self._risk_controls: list[str] = [
            "Circuit breaker with automatic halt on loss threshold breach",
            "Kill switch for immediate trading cessation",
            "Position limit guard per exchange and symbol",
            "Daily loss guard with configurable threshold",
            "Order rate throttling (3 req/s)",
            "HMAC-SHA256 audit trail integrity verification",
            "Live trading safety gate (triple-confirmation)",
            "SEBI static IP validation",
            "OAuth 2FA with auto-logout at IST cutoff",
        ]
        self._position_limits: list[PositionLimitDisclosure] = []

    def add_risk_control(self, control: str) -> None:
        """Add a risk control description to the disclosure."""
        if not control.strip():
            msg = "risk control description cannot be empty"
            raise ConfigError(msg)
        self._risk_controls.append(control)

    def add_position_limit(
        self, exchange: str, max_quantity: Decimal, max_notional: Decimal
    ) -> None:
        """Add position limit information to the disclosure."""
        if not exchange.strip():
            msg = "exchange cannot be empty"
            raise ConfigError(msg)
        if max_quantity <= Decimal("0"):
            msg = "max_quantity must be positive"
            raise ConfigError(msg)
        if max_notional <= Decimal("0"):
            msg = "max_notional must be positive"
            raise ConfigError(msg)
        self._position_limits.append(
            PositionLimitDisclosure(
                exchange=exchange,
                max_quantity=max_quantity,
                max_notional=max_notional,
            )
        )

    def generate_text(self, now_utc: datetime) -> str:
        """Generate plain text risk disclosure document."""
        _validate_utc(now_utc)
        timestamp = now_utc.isoformat()
        doc_id = f"IATB-RD-{now_utc.strftime('%Y%m%d%H%M%S')}"
        risk_controls = self._format_controls_text()
        position_limits = self._format_position_limits_text()
        return _DISCLAIMER_TEMPLATE.format(
            timestamp=timestamp,
            system_name=self._config.system_name,
            system_version=self._config.system_version,
            algo_id=self._config.algo_id,
            risk_controls=risk_controls,
            position_limits=position_limits,
            retention_years=str(self._config.retention_years),
            doc_id=doc_id,
        )

    def generate_html(self, now_utc: datetime) -> str:
        """Generate HTML risk disclosure document."""
        _validate_utc(now_utc)
        timestamp = now_utc.isoformat()
        doc_id = f"IATB-RD-{now_utc.strftime('%Y%m%d%H%M%S')}"
        risk_controls_html = self._format_controls_html()
        position_limits_html = self._format_position_limits_html()
        return _HTML_TEMPLATE.format(
            timestamp=timestamp,
            system_name=self._config.system_name,
            system_version=self._config.system_version,
            algo_id=self._config.algo_id,
            risk_controls_html=risk_controls_html,
            position_limits_html=position_limits_html,
            doc_id=doc_id,
        )

    def save_disclosure(
        self,
        now_utc: datetime,
        fmt: str = "text",
    ) -> Path:
        """Save risk disclosure document to file."""
        _validate_utc(now_utc)
        self._config.output_dir.mkdir(parents=True, exist_ok=True)
        filename = f"risk_disclosure_{now_utc.strftime('%Y%m%d')}"
        if fmt == "html":
            content = self.generate_html(now_utc)
            filepath = self._config.output_dir / f"{filename}.html"
        else:
            content = self.generate_text(now_utc)
            filepath = self._config.output_dir / f"{filename}.txt"
        filepath.write_text(content, encoding="utf-8")
        _LOGGER.info(
            "Risk disclosure saved",
            extra={"path": str(filepath), "format": fmt},
        )
        return filepath

    def _format_controls_text(self) -> str:
        """Format risk controls as text list."""
        lines = []
        for i, control in enumerate(self._risk_controls, 1):
            lines.append(f"  {i}. {control}")
        return "\n".join(lines)

    def _format_position_limits_text(self) -> str:
        """Format position limits as text."""
        if not self._position_limits:
            return "  No custom position limits configured (using SEBI defaults)."
        lines = []
        for limit in self._position_limits:
            lines.append(
                f"  {limit.exchange}: "
                f"Max Qty={limit.max_quantity}, "
                f"Max Notional={limit.max_notional}"
            )
        return "\n".join(lines)

    def _format_controls_html(self) -> str:
        """Format risk controls as HTML list."""
        items = "".join(f"<li>{c}</li>" for c in self._risk_controls)
        return f"<ul>{items}</ul>"

    def _format_position_limits_html(self) -> str:
        """Format position limits as HTML table."""
        if not self._position_limits:
            return "<p>Using SEBI default position limits.</p>"
        rows = "".join(
            f"<tr><td>{lim.exchange}</td><td>{lim.max_quantity}</td>"
            f"<td>{lim.max_notional}</td></tr>"
            for lim in self._position_limits
        )
        return (
            "<table border='1' cellpadding='5'>"
            "<tr><th>Exchange</th><th>Max Quantity</th>"
            f"<th>Max Notional</th></tr>{rows}</table>"
        )


def _validate_utc(dt: datetime) -> None:
    """Validate datetime is UTC-aware."""
    if dt.tzinfo != UTC:
        msg = "datetime must be UTC-aware"
        raise ConfigError(msg)
